// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVcTys7Qpe1QSxPnWn7ZC5Ox1Oldv_IE',
    appId: '1:573024245680:web:650e77d277ad2d5351a875',
    messagingSenderId: '573024245680',
    projectId: 'chat-app-351db',
    authDomain: 'chat-app-351db.firebaseapp.com',
    storageBucket: 'chat-app-351db.firebasestorage.app',
    measurementId: 'G-DD65THB0F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqPpOB9D1EIyCBTpx1HRnHxSao4NacP5o',
    appId: '1:573024245680:android:0100aa40c7a3e55951a875',
    messagingSenderId: '573024245680',
    projectId: 'chat-app-351db',
    storageBucket: 'chat-app-351db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBcpy5Phq04nKQOjcUImQKRDXoA1YOvI',
    appId: '1:573024245680:ios:b1568f10a280639a51a875',
    messagingSenderId: '573024245680',
    projectId: 'chat-app-351db',
    storageBucket: 'chat-app-351db.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCBcpy5Phq04nKQOjcUImQKRDXoA1YOvI',
    appId: '1:573024245680:ios:b1568f10a280639a51a875',
    messagingSenderId: '573024245680',
    projectId: 'chat-app-351db',
    storageBucket: 'chat-app-351db.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVVcTys7Qpe1QSxPnWn7ZC5Ox1Oldv_IE',
    appId: '1:573024245680:web:8718f20693ceb6aa51a875',
    messagingSenderId: '573024245680',
    projectId: 'chat-app-351db',
    authDomain: 'chat-app-351db.firebaseapp.com',
    storageBucket: 'chat-app-351db.firebasestorage.app',
    measurementId: 'G-CZVMM4G5E1',
  );
}
